### ISSUE TITLE
 Transactions between Indian residents must be made using Indian Rupees.

### ISSUE THREAD

**Issue by sheksushant** [parveen7551/paypal#1]
I am from India, the code runs perfectly! but my store gives this error => 

Note: Transactions between Indian residents must be made using Indian Rupees.

Any help appreciated.

**Comment by parveen7551** [comment]
@sushantshek20  I think you should specify your currency as INR in Create method [file](https://github.com/parveen7551/paypal/blob/master/routes/routes.js)

**Comment by sheksushant** [comment]
Thanks!
